version: '3.9'
services:
  db:
    image: postgres:13.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres